---
# vars file for k3s

# supported os
__k3s_supported_os_family:
  - RedHat

# directories
__k3s_installer_directory: /opt/k3s
__k3s_bin_directory: /usr/local/bin

# token files
__k3s_ansible_token_file: /etc/rancher/k3s/ansible-node-token

# config files
__k3s_config_file: /etc/rancher/k3s/config.yaml

# firewalld default zone
__k3s_firewalld_default_zone: public
__k3s_firewalld_trusted_zone: trusted
